In [5]:
# Create a Numpy array filled with all zeros (1d and 2d)
import numpy as np

# 1D array of zeros
zeros_1d = np.zeros(5)
print("1D array of zeros:", zeros_1d)

# 2D array of zeros
zeros_2d = np.zeros((3, 4))
print("2D array of zeros:\n", zeros_2d)


1D array of zeros: [0. 0. 0. 0. 0.]
2D array of zeros:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


Create a Numpy array filled with all zeros (1d and 2d)

In [6]:
# 1D array of ones
ones_1d = np.ones(5)
print("1D array of ones:", ones_1d)

# 2D array of ones
ones_2d = np.ones((3, 4))
print("2D array of ones:\n", ones_2d)


1D array of ones: [1. 1. 1. 1. 1.]
2D array of ones:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


Slice elements from index 4 to the end of the array


In [7]:
# Example array
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Slicing from index 4 to the end
slice_from_4 = arr[4:]
print("Elements from index 4 to the end:", slice_from_4)


Elements from index 4 to the end: [ 5  6  7  8  9 10]


 Slice from the index 3 from the end to index 1 from the end

In [8]:
# Slicing from the index 3 from the end to index 1 from the end
slice_from_end = arr[-3:-1]
print("Elements from index 3 from the end to index 1 from the end:", slice_from_end)


Elements from index 3 from the end to index 1 from the end: [8 9]


. Write the necessary function to get the below output:
Input: arr1 = np.array([[1, 2], [3, 4]]) arr2 = np.array([[10, 20], [30, 40]])


In [9]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[10, 20], [30, 40]])

# Horizontal concatenation
horizontal_concat = np.hstack((arr1, arr2))
print("Horizontal concatenation:\n", horizontal_concat)

# Vertical concatenation
vertical_concat = np.vstack((arr1, arr2))
print("Vertical concatenation:\n", vertical_concat)


Horizontal concatenation:
 [[ 1  2 10 20]
 [ 3  4 30 40]]
Vertical concatenation:
 [[ 1  2]
 [ 3  4]
 [10 20]
 [30 40]]


f. Create a numpy array and find the Sum of All the Elements in the Array

In [10]:
# Example array
arr = np.array([1, 2, 3, 4, 5])

# Sum of all elements
sum_of_elements = np.sum(arr)
print("Sum of all elements in the array:", sum_of_elements)


Sum of all elements in the array: 15


g. Aggregations: Min, Max, and Everything In Between

In [11]:
max_value = max(4, 12, 43.3, 19, 100)
print("Maximum value:", max_value)

values = [4, 12, 43.3, 19]
min_value = min(values)
print("Minimum value:", min_value)

words = ["GoodMorning", "Evening", "algorithm", "programming"]
first_word = min(words)
print("Word occurring 1st among the given set:", first_word)


Maximum value: 100
Minimum value: 4
Word occurring 1st among the given set: Evening


i. Create a list [[4,3,2],[2,1,4]], convert it to a numpy array and sort it along axis 1.

In [12]:
# List
list_2d = [[4, 3, 2], [2, 1, 4]]

# Convert to numpy array
array_2d = np.array(list_2d)

# Sort along axis 1
sorted_array = np.sort(array_2d, axis=1)
print("Sorted array along axis 1:\n", sorted_array)


Sorted array along axis 1:
 [[2 3 4]
 [1 2 4]]


ii. Implement a program to take fruits names from an array of fruits. Sort the array in alphabetical order and display their index position.

In [13]:
# Array of fruits
fruits = np.array(["apple", "orange", "banana", "mango"])

# Sort the array
sorted_fruits = np.sort(fruits)

# Display sorted fruits and their original index positions
original_indices = np.argsort(fruits)
print("Sorted fruits:", sorted_fruits)
print("Original indices of sorted fruits:", original_indices)


Sorted fruits: ['apple' 'banana' 'mango' 'orange']
Original indices of sorted fruits: [0 2 3 1]


In [15]:
import numpy as np

# Create a 2D NumPy array
arr = np.array([[3, 2, 1],
                [6, 1, 4]])

# Sort along rows (axis=1)
sorted_rows = np.sort(arr, axis=1)
print("Sorted along rows:")
print(sorted_rows)

# Sort along columns (axis=0)
sorted_cols = np.sort(arr, axis=0)
print("\nSorted along columns:")
print(sorted_cols)


Sorted along rows:
[[1 2 3]
 [1 4 6]]

Sorted along columns:
[[3 1 1]
 [6 2 4]]
